### ISSUE TITLE
Improve display of i64 values in responses

### ISSUE THREAD

**Issue by UberFarmer** [uber/tcurl#129]
Right now, i64 values in responses show up as indecipherable arrays, like `[0,0,0,0,86,176,103,95]`. They should appear as regular human-readable numbers instead.

**Comment by UberFarmer** [comment]
Very likely related to https://github.com/uber/tcurl/issues/54

**Comment by blampe** [comment]
This is covered in more detail in thriftrw's README ([here](https://github.com/thriftrw/thriftrw-node#timestamps) and [here](https://github.com/thriftrw/thriftrw-node#i64)), but in short Node doesn't support i64s and to get around this you can add an annotation to the field like `(js.type='date')`.
