### ISSUE TITLE
tcurl assumes thrift file name === hyperbahn service name

### ISSUE THREAD

**Issue by Willyham** [uber/tcurl#16]
tcurl assumes that the thrift file name supplied is the exact same name as name registered with hyperbahn.

For example:

```
> ls *.thrift
foo.thrift
> tcurl -p 10.64.79.120:21300 foo Foo::isHealthy -t ./
'Got call response ok'
true
```

```
> ls sync/foo/thrift/*.thrift
sync/foo/thrift/service.thrift
> tcurl -p 10.64.79.120:21300 service Foo::isHealthy -t sync/foo/thrift/
{ [TchannelDeclinedError: no peer available for request]
  type: 'tchannel.declined',
  message: 'no peer available for request',
  isErrorFrame: true,
  codeName: 'Declined',
  errorCode: 4,
  originalId: 2,
  name: 'TchannelDeclinedError',
  fullType: 'tchannel.declined' }
no peer available for request
```

The de facto location for thrift files seems to be `thrift/service.thrift`. It would be handy to at least be able to specify the hyperbahn name. It might be clearer to also accept a thrift file directly with `-f` and a name with `-n`. If `-n` is not specified, the file name is assumed.

This would allow:

* tcurl -p x:x foo Foo::isHealthy -d thrift/files [-n xyz]
* tcurl -p x:x Foo::isHealthy -n foo -f foo/thrift/service.thrift

@Raynos @ShanniLi

**Comment by Raynos** [comment]
This will all be solved by the thriftIdl endpoint in meta.

**Comment by Raynos** [comment]
This is now partially fixed.

You can do `-t a-file.thrift`. If that is broken then we need a new issue.

**Comment by Willyham** [comment]
:+1:
