### ISSUE TITLE
Need the ability to send Ringpop Transport Header

### ISSUE THREAD

**Issue by rssathe** [uber/tcurl#28]
tcurl doesn't have a --headers flag that allows us to send transport tchannel headers

**Comment by rssathe** [comment]
There are existing linter issues/ test issues that I haven't fixed not sure if anything should be done about those.

**Comment by jcorbin** [comment]
Is discussed on #29, please tell us more about what your needs are, transport headers are meant to be a tightly controlled internal detail, and not for arbitrary user extensible headers.

**Comment by rssathe** [comment]
@jcorbin as @Raynos mentioned it is The use case is for tcurling ringpop services which expect shard keys in transport headers

**Comment by Raynos** [comment]
@rssathe  We've had a change of heart; exposing `--headers` leaks too much implementation detail.

Can we change it to `--shardKey=...` ?

**Comment by rssathe** [comment]
@Raynos done
