### ISSUE TITLE
Support thrift annotations

### ISSUE THREAD

**Issue by chucknthem** [uber/tcurl#40]
tcurl fails to parse thrift idls with annotations e.g. 

test.thrift:
```
struct Test {
    1: string foo ( is_red = "yes" );
    2: string bar
}
```
```
$ tcurl -H /path/to/hosts.json -t test.thrift test Test:test
```
```
undefined:6350
      throw peg$buildException(null, peg$maxFailExpected, peg$maxFailPos);
            ^
SyntaxError: Expected "/*", "0x", "=", "xsd_attributes", "xsd_nillable", "xsd_optional", "}", [+\-], [0-9], comment, end of line, list separator or whitespace but "(" found.
```

We use annotations as hints for custom code gen. The normal thrift parser can parse them. Can we add them to whatever parser tcurl uses?

**Comment by Raynos** [comment]
We are working on migrating from `thriftify` to `thriftrw`. `thriftrw` supports annotations.

cc @kriskowal

**Comment by kriskowal** [comment]
This is fixed.
