### ISSUE TITLE
Supporting health checks

### ISSUE THREAD

**Issue by Raynos** [uber/tcurl#9]
In production we want an easy way of doing health checks with tcurl.

There are a few options:

## as=raw endpoint

In your language of choice; implement an endpoint that uses the raw encoding.

Then use `tcurl -p host:port {serviceName} {endpointName} --raw` to hit it; 

This works today

## Using a thrift health check

To do a thrift health check you need the IDL file; this is rather inconvenient; to really do so we want to support pre-flight IDL fetches

 - In all languages; implement as=raw endpoint called `thrift_idl_v1` that returns the thrift IDL as utf8.
 - Add a feature to tcurl to support `tcurl -p host:port --thrift {serviceName} {endpointName}`. If the `--thrift` flag is set then do a pre-flight IDL fetch request followed by the actual request

This relies on #10 

## Support machine readable output

The tcurl binary outputs "Got call response ok" which we should have a way of stripping; this makes matching with existing tooling easier, for example nagios

 - Add a `--quiet` flag that only outputs response arg3.

This relies on #11

## Related issues

 - tcurl #10
 - tcurl #11
 - tchannel https://github.com/uber/tchannel/issues/907

**Comment by Raynos** [comment]
cc @xichen2020 @prashantv @jsu1212

**Comment by Raynos** [comment]
Another idea

## A shared IDL that all services implement.

To do better introspection into any service using tcurl we could force all services to implement a shared IDL file.

For example

```thrift
service Meta {
  void health_v1()
  string thrift_idl_v1()
}
```

We can bake this IDL directly into tcurl and we would have all services implement it; this allows us to add new useful shared endpoints in the future.

We should probably expose this IDL file from tchannel so it can be imported from a shared place.

**Comment by breerly** [comment]
v1?

**Comment by abhinav** [comment]
Method names are usually camelCase in Thrift IDLs.

Health check needs to be able to return something (bool or enum) or throw an exception.

Also, thoughts on removing `v1`? Breaking changes to method signatures will be problematic regardless of approach. How does the version number in method names help?

**Comment by ShanniLi** [comment]
Let's make v1 go away.

No need to return true, since the result body should has ok=true when succeeded.

**Comment by Raynos** [comment]
### Casing

`camelCase` vs `snake_case` is a general discussion to have; I dont care too deeply.

### version numbers

As for putting version numbers in endpoints; I strongly recommend this as reality says that breaking changes happen. My biggest mistake with sirvice was not putting versions in everything.

Now **especially** for a shared `Meta` thrift IDL that is going to be hardcoded in a `tcurl` debian that wil be shared among all languages.

We may want to implement a `health_v2` that returns a scalar or a struct instead of a boolean.

 - One could argue that you can pick unique method names instead of postfixing the version
 - One could argue that the v1 can be health and v2 can be `health_v2`

Either way versions are a reality and I strongly encourage people to put a v1 in every endpoint because that is reality; you will make  breaking changes.

Any belief that thrift has one version and you never make breaking changes is a lie and that's not how it works

**Comment by ShanniLi** [comment]
"One could argue that you can pick unique method names instead of postfixing the version" -- a new name is better when a new feature is implemented.

**Comment by blampe** [comment]
Casing: Whatever we choose here will basically establish a convention that other people will start emulating. The convention in existing services has been camelCase, so I'm OK with that for consistency.

Versioning: I really don't want to encourage people to make breaking changes. We should be encouraging a mindset that supports smart Thrift usage. It *is* possible to use Thrift correctly.

Return type: I'm in favor of returning a boolean. The app might be able to listen/serve traffic but has failed to load some resources or something and isn't actually healthy enough for traffic. I think this would better support some business logic in the health check.

**Comment by prashantv** [comment]
+1 for camelCase.

Return type: prefer returning something other than void, and preferably a struct (which can be extended to return more info in future).

**Comment by abhinav** [comment]
I don't have a strong opinion on the health check return type. It would be nice if the health check could do some extra checks but most people will implement it to return right away. I don't know if we want to differentiate between light and deep health checks. 

Regarding more complex structs on health checks: sounds like a great idea in theory, but for most use cases, service health is treated as binary. Callers will treat services as either working or not working. I doubt they will alter their behavior because the service is in a partially degraded state.

**Comment by junchaowu** [comment]
I prefer to make the health endpoint as simple as possible. Since this is a meta endpoint required on all service, it will affect lots of service. For more complex functionality, services can create their own.

**Comment by ShanniLi** [comment]
+1 for making the health check simple. Most of our existing health checks are simple health checks. We need to have a very good reason to convince people implement more complex ones. For complex checks, stats and alerts should be used instead.

**Comment by Raynos** [comment]
Health checks are in.
